import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { readContent } from "./content-lib.mjs";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const content = readContent(root);
const generatedDir = path.join(root, "src", "generated");
fs.mkdirSync(generatedDir, { recursive: true });
fs.writeFileSync(path.join(generatedDir, "content.ts"), `// Generated by scripts/content-build.mjs. Do not edit.\nexport const venue = ${JSON.stringify(content.venue, null, 2)} as const;\nexport const events = ${JSON.stringify(content.events, null, 2)} as const;\nexport const notices = ${JSON.stringify(content.notices, null, 2)} as const;\n`);

const xml = (value) => value.replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;").replaceAll('"', "&quot;").replaceAll("'", "&apos;");
const urls = ["https://www.altrospazio.org/", "https://www.altrospazio.org/eventi", ...content.events.map((event) => `https://www.altrospazio.org/eventi/${event.slug}`)];
fs.writeFileSync(path.join(root, "public", "sitemap.xml"), `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${urls.map((url) => `  <url><loc>${xml(url)}</loc></url>`).join("\n")}\n</urlset>\n`);
